### ISSUE TITLE
Incorrect feature reading

### ISSUE THREAD

**Issue by Xopre** [RGNC/plingua#1]
Hello there,

I'm trying to use the features of P-Lingua 5.0 to include stochastic constants, as in the following minimal example:

```plingua
@include "minimal_sc_model_int_t.pli
@mu = [ ]'0;
@ms(0) = a;
[a -> b]'0 @sc=1;
```

With `minimal_sc_mode_int_t.pli` defined as follows:

```plingua
!stochastic_rule
{
  [ u -> v ]'h @ sc(int_t); 
}
@model(stochastic) = stochastic_rule;
```

However, after running `plingua minimal_sc_system.pli -o minimal_sc_system_int_t.xml -f xml` the resultant `xml` file has the following feature, associated to the only rule present in the system:

```xml
<features size="dynamic">
	<value0>
		<key>
			<id>0</id>
		</key>
		<value>
			<type>8</type>
			<id>1</id>
		</value>
	</value0>
	<value1>
		<key>
			<id>1</id>
		</key>
		<value>
			<type>0</type>
			<value></value>
		</value>
	</value1>
</features>
```

As you can see, the `sc` parameter (fourth line from the bottom) presents a strange value. The same happens using instead of `int_t` the types `double_t, long_t` and `prob_t`. However, I have found that if a value of 100 or 101 is given to the `sc` feature, in the `xml` file it appears as "d", "e" or "f". Perhaps every feature is taken as an ASCII character? This would be coherent with the fact that the `value>(type, value)` branch of the feature presents in all those cases the type "0", which could mean "char".

Looking forward to hearing from you,

Kind regards,

Xopre

**Comment by Ignacio-Perez** [comment]
Hello,

Thank you very much for your feedback. The bug has been fixed.

Ignacio
